name: Trigger KaneAI Test Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-kaneai-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger KaneAI test using LambdaTest API
        run: |
          echo "Triggering KaneAI CI test run"
          curl -u "${{ secrets.LT_USERNAME }}:${{ secrets.LT_ACCESS_KEY }}" \
          -X POST https://test-manager-api.lambdatest.com/api/v1/ata/v1/hyperexecute\
          -H "Content-Type: application/json" \
          -d '{
            "concurrency": 2,
            "title": "KaneAI GitHub Trigger",
            "region": "us",
            "replaced_url": "https://your-staging-app.com"
          }'
