name: Trigger KaneAI Test Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-kaneai-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger KaneAI test using LambdaTest API
        run: |
          echo "Triggering KaneAI CI test run"
          response=$(curl --location "https://test-manager-api.lambdatest.com/api/v1/ata/v1/hyperexecute" \
          --header "Content-Type: application/json" \
          --header "Authorization: Basic ${{ secrets.LT_AUTH_BASE64 }}" \
          --data '{
            "test_run_id": "01JZSHN86KY75PZ53T0ACQ7M4T",
            "concurrency": 1,
            "title": "GitHub CI Trigger"
          }')
          echo "Response: $response"
