name: Trigger KaneAI Test Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-kaneai-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger KaneAI test using LambdaTest API
        run: |
          echo "Triggering KaneAI CI test run"
          curl -u "${{ secrets.LT_USERNAME }}:${{ secrets.LT_ACCESS_KEY }}" \
          -X POST https://test-manager-api.lambdatest.com/api/v1/test/v1/hyperexecute \
          -H "Content-Type: application/json" \
          -d '{
            "test_run_id": "01JZSHN86KY75PZ53T0ACQ7M4T",
            "concurrency": 2,
            "title": "KaneAI GitHub Trigger"
          }'

